[package]
name = "web_framework_derive"
version = "0.1.0"
opt-level = 0
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
log = "0.4"
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
