[package]
name = "web-framework-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
mockito = "0.31"

[dev-dependencies]
mockito = "0.31"
